"""add Department

Revision ID: 992a43a2898e
Revises: 32cf2e63b3c6
Create Date: 2024-01-15 19:53:18.938890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992a43a2898e'
down_revision = '32cf2e63b3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
